version: "3.8"

services:
  app:
    build: .
    image: student-mgmt-app:latest
    container_name: student-mgmt-app
    ports:
      - "5000:5000"
    volumes:
      - app-data:/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: sms-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: sms-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  app-data:
