---
- name: Deploy Student Management System container
  hosts: app_servers
  gather_facts: false
  vars:
    image: "tahereemk/student-mgmt-app:latest"
    container_name: student-mgmt-app
    host_port: 5000

  tasks:
    - name: Pull latest application image
      ansible.builtin.command: docker pull {{ image }}

    - name: Remove existing container (if any)
      ansible.builtin.command: docker rm -f {{ container_name }}
      ignore_errors: true

    - name: Run application container
      ansible.builtin.command: >
        docker run -d --name {{ container_name }}
        --restart unless-stopped
        -p {{ host_port }}:5000
        -v sms-data:/data
        {{ image }}
